version: '3'

services:
  web:
    build: .
    volumes:
      - .:/web
    expose:
      - "9001"

  nginx:
    image: nginx:1.13.8
    links:
      - web:web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/web
    ports:
     - "80:80"
    command:
      /bin/bash -c "nginx -g 'daemon off;'"